import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'AI Disclaimer — AcquisitionOS',
  description: 'Disclaimer regarding AI-powered features in AcquisitionOS.',
};

export default function AIDisclaimerPage() {
  return (
    <article className="container-app px-4 sm:px-6 py-12 sm:py-16">
      <div className="max-w-3xl mx-auto">
        {/* Title */}
        <div className="mb-10">
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-3">
            AI Disclaimer
          </h1>
          <p className="text-xs text-muted-foreground italic">Last updated: March 4, 2026</p>
          <div className="mt-4 h-1 w-16 rounded-full bg-primary" />
        </div>

        {/* Intro */}
        <p className="text-sm text-muted-foreground leading-relaxed mb-6">
          AcquisitionOS incorporates artificial intelligence (&quot;AI&quot;) and machine learning technologies to power
          several features within our client acquisition platform. This AI Disclaimer explains the nature, limitations,
          and appropriate use of these AI-powered capabilities. By using AI features in AcquisitionOS, you acknowledge
          and accept the terms described below.
        </p>

        {/* Section 1 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">1. AI-Powered Features</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-2">
            The following AcquisitionOS features utilize AI and machine learning models:
          </p>
          <ul className="list-disc pl-6 text-sm text-muted-foreground leading-relaxed mb-4 space-y-1">
            <li><strong>Lead Scoring:</strong> AI evaluates and ranks potential leads based on relevance, engagement likelihood, and conversion probability. Scores are probabilistic estimates, not guarantees.</li>
            <li><strong>Sales Coaching:</strong> AI-driven advice on objection handling, negotiation strategies, and sales scripts. Suggestions are based on general patterns and may not apply to every situation.</li>
            <li><strong>Outreach Suggestions:</strong> AI-generated personalized outreach messages, email templates, and follow-up sequences. Content is created based on inputs you provide and should be reviewed before sending.</li>
            <li><strong>Competitive Analysis:</strong> AI analyzes publicly available competitor data and market positioning. Insights are based on available data and may not capture all relevant factors.</li>
            <li><strong>Predictive Insights:</strong> AI forecasts deal outcomes, pipeline velocity, and revenue projections. These are estimates and should not be treated as certain predictions.</li>
          </ul>
        </section>

        {/* Section 2 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">2. Nature of AI-Generated Content</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-2">
            Content and recommendations generated by AcquisitionOS AI features are provided for informational and
            productivity purposes only. You must understand that:
          </p>
          <ul className="list-disc pl-6 text-sm text-muted-foreground leading-relaxed mb-4 space-y-1">
            <li>AI-generated content does not constitute professional legal, financial, tax, or business advice</li>
            <li>AI-generated outreach messages and sales scripts are starting points that should be personalized and reviewed before use</li>
            <li>Lead scores and predictions are statistical estimates and do not guarantee any specific outcome or conversion rate</li>
            <li>Similar AI outputs may be generated for multiple users with similar inputs</li>
            <li>AI models may produce outputs that contain inaccuracies, outdated information, or irrelevant suggestions</li>
          </ul>
        </section>

        {/* Section 3 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">3. Accuracy Limitations</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-2">
            While we strive to provide useful and accurate AI outputs, the technology has inherent limitations:
          </p>
          <ul className="list-disc pl-6 text-sm text-muted-foreground leading-relaxed mb-4 space-y-1">
            <li>AI models may generate plausible-sounding but incorrect or misleading information (hallucinations)</li>
            <li>AI analysis is based on the data provided and available training data, which may not cover all relevant contexts</li>
            <li>Lead scores reflect patterns in historical data and may not accurately predict individual outcomes</li>
            <li>AI may not account for recent market changes, regulatory updates, or emerging competitive dynamics</li>
            <li>Language and cultural nuances may not always be correctly interpreted</li>
          </ul>
        </section>

        {/* Section 4 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">4. User Responsibility</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-2">
            You are solely responsible for:
          </p>
          <ul className="list-disc pl-6 text-sm text-muted-foreground leading-relaxed mb-4 space-y-1">
            <li>Reviewing, verifying, and editing all AI-generated content before sending, publishing, or relying on it</li>
            <li>Ensuring outreach messages comply with applicable anti-spam laws and regulations (e.g., CAN-SPAM, GDPR)</li>
            <li>Making final decisions on lead engagement, deal strategies, and business actions</li>
            <li>Seeking independent professional advice (legal, financial, or otherwise) where appropriate</li>
            <li>Ensuring that AI-assisted decisions do not unlawfully discriminate against any individual or group</li>
            <li>Any consequences arising from your use of AI-generated content or recommendations</li>
          </ul>
        </section>

        {/* Section 5 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">5. Data Used for AI Processing</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-2">
            When you use AI features, the following data may be processed by AI models:
          </p>
          <ul className="list-disc pl-6 text-sm text-muted-foreground leading-relaxed mb-4 space-y-1">
            <li>Lead contact information and engagement history submitted for scoring or analysis</li>
            <li>Outreach parameters (tone, length, industry context) used to generate personalized messages</li>
            <li>Sales conversation context provided for coaching suggestions</li>
            <li>Competitor names and publicly available market data for competitive analysis</li>
          </ul>
          <p className="text-sm text-muted-foreground leading-relaxed">
            AI processing may be performed by third-party providers (such as OpenAI and Anthropic) under strict data
            processing agreements. These providers do not use your data to train their models without explicit consent.
            For details, see our{' '}
            <a href="/legal/privacy" className="text-primary font-medium hover:underline">Privacy Policy</a>.
          </p>
        </section>

        {/* Section 6 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">6. No Automated Legal Decisions</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-4">
            AcquisitionOS does not use AI to make automated decisions that produce legal effects or similarly
            significantly affect you. All AI features are advisory and assistive. You retain full control and
            authority over all business decisions, outreach actions, and lead engagement strategies. AI-generated
            suggestions can always be reviewed, modified, or disregarded at your discretion. For more information,
            see our{' '}
            <a href="/legal/gdpr" className="text-primary font-medium hover:underline">GDPR Data Processing Agreement</a>.
          </p>
        </section>

        {/* Section 7 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">7. Human Oversight</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-4">
            We maintain human oversight of our AI systems. This includes regular review of AI model outputs for
            quality and accuracy, monitoring for bias or harmful patterns, and periodic updates to improve performance.
            If you encounter AI-generated content that appears inaccurate, biased, or harmful, please report it to
            us at support@acquisitionos.com so we can investigate and improve our systems.
          </p>
        </section>

        {/* Section 8 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">8. Updates to AI Models</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-4">
            We may update, modify, or replace the AI models powering AcquisitionOS features at any time. Such updates
            may change the outputs, accuracy, or behavior of AI features. We will notify users of material changes
            through our standard update channels. Continued use of AI features after an update constitutes acceptance
            of the updated functionality.
          </p>
        </section>

        {/* Section 9 */}
        <section className="mb-8">
          <h2 className="text-xl font-bold mb-3">9. Contact Information</h2>
          <p className="text-sm text-muted-foreground leading-relaxed mb-2">
            For questions about our AI features or to report issues with AI-generated content:
          </p>
          <ul className="list-disc pl-6 text-sm text-muted-foreground leading-relaxed space-y-1">
            <li><strong>Email:</strong> legal@acquisitionos.com</li>
            <li><strong>Website:</strong> acquisitionos.com</li>
          </ul>
        </section>
      </div>
    </article>
  );
}
